config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#welcome", as: :welcome
  get "portfolio", to: "pages#portfolio", as: :portfolio
  get "contact", to: "pages#contact", as: :contact
  get "about", to: "pages#about", as: :about
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def portfolio
  end

  def contact 
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>Shane's Portfolio</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Serif:wdth,wght@67.4,282&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <header>
    <h2><%= link_to "SHANE WOODMAN", welcome_path %> </h2>
    <nav>
      <ul>
        <li><%= link_to "Portfolio", portfolio_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </header>
  
  <body>
    <%= yield %>
  </body>

  <footer>
    <ul>
      <li><%= link_to image_tag("https://live.staticflickr.com/65535/53919605045_b4b97b1fd9_q.jpg>"), "https://www.linkedin.com/in/shane-woodman-5275982b6/", target: "_blank" %>
      </li>
      <li><%= link_to image_tag("https://live.staticflickr.com/65535/53919598856_1c31cd52fd_m.jpg"), "https://github.com/Swoodman90", target: "_blank" %>
      </li>
    </ul>
  </footer>
  
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html>
</html>

app/views/pages/portfolio.html.erb
<!DOCTYPE html>
<html>
  <main>
    <%= image_tag("https://live.staticflickr.com/65535/53924899148_4a793d2ed0_c.jpg") %>
  </main>
  
</html>

app/views/pages/welcome.html.erb
<!DOCTYPE html>
<html>
  <main>
    <section>
      <p>Hey, I'm Shane.<br><br>
      A software engineer from North Carolina, excited to solve problems in the professional world. 
      <br><br>
      <button><%= link_to "View My Work", portfolio_path %></button></p>
      <%= image_tag("https://live.staticflickr.com/65535/53921793988_0ae62865f6_b.jpg") %>
    </section>
  </main>

</html>